<a href="https://colab.research.google.com/github/Desh-Deepak1/Colab-Projects/blob/main/NumpyPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])

In [ ]:
arr1 = np.array([1,2,3])

In [ ]:
arr2 = np.array([6,7,8])

In [ ]:
arr1 + arr2

array([ 7,  9, 11])

In [ ]:
arr3 =np.array([1,2,3,4,5 , 6])

In [ ]:
arr3[-2]

np.int64(5)

In [ ]:
arr3[1:3]

array([2, 3])

In [ ]:
arr3.shape

(6,)

In [ ]:
arr3.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr3 + 1

array([2, 3, 4, 5, 6, 7])

In [ ]:
arr3 *2

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
m1 = np.array([[1,2], [3,4]])
m2 = np.array([[5,6],[7,8]])

In [ ]:
np.dot(m1 ,m2)

array([[19, 22],
       [43, 50]])

In [ ]:
np.mean(arr3)

np.float64(3.5)

In [ ]:
np.max(arr3)

np.int64(6)

In [ ]:
np.std(arr3)

np.float64(1.707825127659933)

In [ ]:
np.random.rand(5)

array([0.09357086, 0.49154702, 0.35323386, 0.14230194, 0.33542001])

In [ ]:
np.random.randint(1000,9999)

2602

In [ ]:
arr =[1,2,3,np.nan, 4 ,5 ,6]

In [ ]:
arr

[1, 2, 3, nan, 4, 5, 6]

In [ ]:
np.isnan(arr)

array([False, False, False,  True, False, False, False])

In [ ]:
import time

In [ ]:
L1 = list(range(100000000))
start =time.time()
sum(L1)
end = time.time()
print(end-start)

0.7837550640106201


In [ ]:
start =time.time()
np.sum(L1)
end = time.time()
print(end-start)

4.550435543060303


# **PANDAS**

In [ ]:
import pandas as pd

In [ ]:
# People :p1 , p2 , p3
# Age : 20,30,40

In [ ]:
d = { 'People':['p1','p2','p3'], 'Age':[20,30,40]}

In [ ]:
df =pd.DataFrame(d)

In [ ]:
df

,People,Age
0,p1,20
1,p2,30
2,p3,40


In [ ]:
pd.read_excel("student_dataset.xlsx")

,Student ID,Name,Gender,Age,Math,Science,English,History
0,S001,Alice,F,14,85,92,78,88
1,S002,Bob,M,15,62,55,70,60
2,S003,Charlie,M,14,95,88,91,93
3,S004,Diana,F,15,74,70,82,77
4,S005,Ethan,M,14,45,50,55,48
5,S006,Fiona,F,15,90,94,88,91
6,S007,George,M,14,68,72,65,70
7,S008,Hannah,F,15,81,85,90,83
8,S009,Ian,M,14,77,65,72,68
9,S010,Julia,F,15,55,60,58,62


In [ ]:
df

,People,Age
0,p1,20
1,p2,30
2,p3,40


In [ ]:
df.to_csv("sample.CSV")

In [ ]:
pd.read_csv("sample.CSV")

,Unnamed: 0,People,Age
0,0,p1,20
1,1,p2,30
2,2,p3,40


In [ ]:
df.to_csv("sample.CSV", index = False)

In [ ]:
pd.read_csv("sample.CSV")

,People,Age
0,p1,20
1,p2,30
2,p3,40
